config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
  end
  namespace :admins_backoffice do
    get 'admins/index'
    get 'welcome/index'
    resources :admins
    resources :subjects
    resources :questions
  end

  devise_for :users 
  devise_for :admins
 
  get 'inicio', to: 'site/welcome#index'

  root to: 'site/welcome#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :subject, inverse_of: :questions
  has_many :answers
  accepts_nested_attributes_for :answers, reject_if: :all_blank, allow_destroy: true
end

app/models/subject.rb
class Subject < ApplicationRecord
    has_many :questions
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destroy]
  before_action :params_admin, only: [:update, :destroy]

  def index
    @admins = Admin.all.page(params[:page]).per(5)
  end

  def new 
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Administrador cadastrado com sucesso!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @admin.update(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Administrador atualizado com sucesso!"
    else
      render :edit
    end
  end

  def destroy
    if @admin.destroy(params_admin)
      redirect_to admins_backoffice_admins_path, notice: "Administrador excluído com sucesso!"
    else
      render :index
    end
  end

  def show 
    redirect_to admins_backoffice_admins_path, notice: "Administrador excluído com sucesso!"
  end

  private

  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end

  def set_admin 
    @admin = Admin.find(params[:id])
  end

  def verify_password 
    if params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end
end

app/controllers/admins_backoffice/questions_controller.rb
class AdminsBackoffice::QuestionsController < AdminsBackofficeController
  before_action :set_question, only: [:edit, :update, :destroy]
  before_action :get_subjects, only: [:new, :edit]
    
  
  def index
    @questions = Question.includes(:subject).order(:description).page(params[:page]).per(5)
  end
  
  def new 
    @question = Question.new
  end
  
  def create
    @question = Question.new(params_question)
    if @question.save
      redirect_to admins_backoffice_questions_path, notice: "Questão cadastrada com sucesso!"
    else
        render :new
    end
  end
  
  def edit
  end
  
  def update
    if @question.update(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão atualizada com sucesso!"
    else
      render :edit
    end
  end
  
  def destroy
    if @question.destroy(params_question)
      redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
    else
      render :index
    end
  end
  
  def show 
    redirect_to admins_backoffice_questions_path, notice: "Questão excluída com sucesso!"
  end
  
  private
  
  def params_question
    params.require(:question).permit(:description, :subject_id,
    answers_attributes: [:id, :description, :correct, :done, :_destroy]
    )
  end
  
  def set_question 
    @question = Question.find(params[:id])
  end

  def get_subjects
    @subjects = Subject.all
  end
end

app/controllers/admins_backoffice/subjects_controller.rb
class AdminsBackoffice::SubjectsController < AdminsBackofficeController
    before_action :set_subject, only: [:edit, :update, :destroy]
    
  
    def index
      @subjects = Subject.all.order(:description).page(params[:page]).per(5)
    end
  
    def new 
      @subject = Subject.new
    end
  
    def create
      @subject = Subject.new(params_subject)
      if @subject.save
        redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área cadastrado com sucesso!"
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      if @subject.update(params_subject)
        redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área atualizado com sucesso!"
      else
        render :edit
      end
    end
  
    def destroy
      if @subject.destroy(params_subject)
        redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área excluído com sucesso!"
      else
        render :index
      end
    end
  
    def show 
      redirect_to admins_backoffice_subjects_path, notice: "Assunto/Área excluído com sucesso!"
    end
  
    private
  
    def params_subject
      params.require(:subject).permit(:description)
    end
  
    def set_subject 
      @subject = Subject.find(params[:id])
    end
  
  end
  

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
    before_action :authenticate_admin!
    layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    layout :layout_by_resource

    protected

    def layout_by_resource
        devise_controller? ? "#{resource_class.to_s.downcase}_devise" : "application"
    end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
    layout 'site'
end

app/controllers/users_backoffice/welcome_controller.rb
class UsersBackoffice::WelcomeController < UsersBackofficeController
  def index
  end
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
    before_action :authenticate_user!
    layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/questions_helper.rb
module AdminsBackoffice::QuestionsHelper
end

app/helpers/admins_backoffice/subjects_helper.rb
module AdminsBackoffice::SubjectsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/welcome_helper.rb
module UsersBackoffice::WelcomeHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins_backoffice/questions/_answers_fields.html.erb
<div class="nested-fields">
    <%= f.label :description %> </br>
    <%= f.text_field :description %>
    <%= f.check_box :correct %> Correta?

    <%= link_to_remove_association('Remover', f) %>
</div>

app/views/admins_backoffice/questions/edit.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form',
            locals: {action_message: 'Editando'} %>

app/views/admins_backoffice/questions/index.html.erb
<div class="container">

  <h1>Listando Perguntas</h1>
    
  <%= link_to new_admins_backoffice_subject_path do %>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <button class="btn btn-success" type="button">Criar Nova Perguntas</button>
    </div>               
  <% end %>
      
      
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Pergunta</th>
        <th scope="col">Assunto</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @questions.each do |question| %>
      <tr>
        <th scope="row"><%= question.id %></th>
        <td><%= question.description.truncate(50) %></td>
        <td><%= question.subject.description.truncate(30) %></td>
        <td>
          <%= link_to edit_admins_backoffice_question_path(question)  do %>
              <button class="btn btn-primary" type="button">Editar</button>
          <% end %>
        </td>
        <td>
          <%= link_to admins_backoffice_question_path(question), method: :delete, data: { confirm: "Deseja realmente excluir esta pergunta?"}  do %>
              <button class="btn btn-danger" type="button">Deletar</button>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-grid gap-2 col-6 mx-auto" >
      <%= paginate @questions %>
  </div>

  <%= link_to admins_backoffice_welcome_index_path do %>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
      <button class="btn btn-primary" type="button">Voltar para admins_backoffice</button>
    </div>               
  <% end %>

</div>

app/views/admins_backoffice/questions/new.html.erb
<%= render partial: 'admins_backoffice/questions/shared/form',
            locals: {action_message: 'Nova Pergunta'} %>

app/views/admins_backoffice/subjects/edit.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
            locals: {action_message: 'Editando'} %>

app/views/admins_backoffice/subjects/index.html.erb
<div class="container">

  <h1>Listando Assuntos/Áreas</h1>
    
  <%= link_to new_admins_backoffice_subject_path do %>
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <button class="btn btn-success" type="button">Criar Novo Assunto</button>
    </div>               
  <% end %>
      
      
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Id</th>
        <th scope="col">Descrição</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @subjects.each do |subject| %>
      <tr>
        <th scope="row"><%= subject.id %></th>
        <td><%= subject.description %></td>
        <td>
          <%= link_to edit_admins_backoffice_subject_path(subject)  do %>
              <button class="btn btn-primary" type="button">Editar</button>
          <% end %>
        </td>
        <td>
          <%= link_to admins_backoffice_subject_path(subject), method: :delete, data: { confirm: "Deseja realmente excluir este assunto?"}  do %>
              <button class="btn btn-danger" type="button">Deletar</button>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div class="d-grid gap-2 col-6 mx-auto" >
      <%= paginate @subjects %>
  </div>

  <%= link_to admins_backoffice_welcome_index_path do %>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
      <button class="btn btn-primary" type="button">Voltar para admins_backoffice</button>
    </div>               
  <% end %>

</div>

app/views/admins_backoffice/subjects/new.html.erb
<%= render partial: 'admins_backoffice/subjects/shared/form',
            locals: {action_message: 'Novo'} %>

app/views/admins_backoffice/welcome/index.html.erb
<h1>AdminsBackoffice::Welcome#index</h1>
<p>Find me in app/views/admins_backoffice/welcome/index.html.erb</p>

<p><%= link_to 'Fazer logoff [Administrador]', destroy_admin_session_path, method: :delete %></p>

app/views/site/welcome/index.html.erb
<h1>Site::Welcome#index</h1>
<p>Find me in app/views/site/welcome/index.html.erb</p>

<% if user_signed_in? %>
    <p>Usuário ESTÁ logado</p>
    <p><%= current_user.email %></p>
<% else %>
    <p>Usuário NÃO está logado</p>
<% end %>

<% if admin_signed_in? %>
    <p>Administrador ESTÁ logado / <%= current_admin.email %> </p>
<% else %>
    <p>Administrador NÃO está logado</p>
<% end %>